### PR TITLE
feat: Use environment feature state instead of fetching feature states

### LINKED ISSUE #3301: Browsing features too slow when there are lots of features
### How are you running Flagsmith

- [X] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [ ] Self Hosted at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

When there is a project with many feature flags (700+ in this case), the page for browsing flags becomes very slow and unresponsive. Searching a flag takes over 20 seconds.

I suspect most calls to `/api/v1/environments/<env-id>/featurestates/` are unnecessary.

### Steps To Reproduce

1. Create lots of feature flags
2. Try to search for a feature flag

### Expected behavior

Page should be responsive.

### Screenshots

https://github.com/Flagsmith/flagsmith/assets/7023385/48d4cb95-41e7-42bf-bb92-a12b24dc05b6

### PR DESCRIPTION
**Pull request by kyle-ssg**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

In order for the feature list page to function, it needs access to the features and feature states.

Prior to this the frontend got all feature states when fetching features and matched them up. Now that the backend returns the feature states in the features, this PR adjusts the Frontend to use that rather than fetching them.

Resolves #3301

## How did you test this code?

- Filtered , created and updated features
- Created and updated versioned features
- Created and updated MV features

### CODE REVIEW

**Review by matthewelwell — COMMENTED** [review]
I've tested this and it looks good to me 👍 . Since it's quite a critical change, I'd love to get another pair of eyes on it as well, although I guess the E2E tests will cover this part of the app significantly.

**Review by matthewelwell — APPROVED** [review]

**Comment by novakzaballa** [comment]
@kyle-ssg why we don't use the RTK here?

**Comment by kyle-ssg** [comment]
It’ll be very difficult to migrate this given how integral and widely used it is. Though I did make versioning use it to make it easier when we do.

**Review by novakzaballa — APPROVED** [review]
LGTM. Also, the functional tests are working.

**Pull request merged**
