### PR TITLE
chore: Plan based access UI

### LINKED ISSUE #3464: Add more relevant links out to closed source features in our open source version
We sometimes have folk running Flagsmith open source becoming confused about what is open and what isn't - a lot people get sent the link to [this page](https://docs.flagsmith.com/version-comparison)!

We should have a consistent UI experience to make sure that closed features are included in the open source version with relevant links out to the relevant docs area explaining what plan / version you need to be running to get access to that feature.

### PR DESCRIPTION
**Pull request by kyle-ssg**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

- Adds a consistent approach to plan based access by adding the following components
  - Plan based banner
  - Plan based page
  - Plan based setting
  - Plan based select option

- Adds a central location for paid features, their plan and their description
- Adds a consistent UX based on whether the app is running as SaaS or self-hosted
image

- Adds a video preview to some features, accessible via hovering the feature or on the page depending on the UI.

image

## Testing

Testing, as free self hosted or saas view the following features

- 2FA
image

- Change Requests

image
image

- Audit Log
image

- Create 2nd project
image

- Flag owners
image

- RBAC
image
image
image

- Stale flag detection
image

- Realtime 
image

- Versioning
image

### CODE REVIEW

**Review by novakzaballa — COMMENTED** [review]
The code looks good, but the multi-factor authentication feature doesn't show a banner when I'm on a free plan.



https://github.com/Flagsmith/flagsmith/assets/41410593/a765ad08-ffc0-464e-930a-265101edb0d6

**Review by rolodato — COMMENTED** [review]
Overall looks good, here's my feedback:

The blurb for free orgs being limited to 1 project ("View and manage multiple projects in your organisation") is not very informative. I would suggest something like "Free organisations are limited to one Flagsmith project"

The blurb for forcing 2FA is also not informative of the benefits - we could reword to something like "Improve security compliance across your organisation" (sorry I'm terrible at writing this type of copy 🙃)

The blurb for audit logs could also be more value-oriented. For example: "View and search through a history of all changes made in your Flagsmith organisation". Again, there are probably better ways to word this than what I suggested.

On self-hosted, instead of linking from the "🔒 Enterprise" badge to https://www.flagsmith.com/contact-us, have we considered linking to https://www.flagsmith.com/pricing? This would be more in line with SaaS where we link to the billing page that shows a comparison of all plans. I think it's better to showcase all the benefits of an Enterprise plan in one place instead of going directly to the Contact Us page.

For change requests, we don't need to mention change requests again in the blurb. It could be shortened to "Add a 4-eyes approval mechanism to your feature changes."

This PR is also be a good opportunity to remove the SAML plan and flag check here: https://github.com/Flagsmith/flagsmith/blob/117f72abb7ce74d75b05a8c5338245c926a39193/frontend/web/components/pages/OrganisationSettingsPage.js#L236-L239

I'm not a fan of the videos to showcase how these gated features work. I understand the intention to quickly show an overview without linking to the docs page, but they're more effort to maintain (the video content itself and how the videos interact with the page layout, which we're not seeing very often during our testing and day-to-day usage) and cannot easily be linked to. I'd prefer to invest in the docs pages and optionally add a secondary action item like "View docs". I also found the videos that display on hover to be jarring/unexpected.

Lastly, are there UTM codes we could/should use for any links here to gauge interest on how they're interacted with?

**Comment by kyle-ssg** [comment]
> The blurb for free orgs being limited to 1 project ("View and manage multiple projects in your organisation") is not very informative. I would suggest something like "Free organisations are limited to one Flagsmith project"
> The blurb for forcing 2FA is also not informative of the benefits - we could reword to something like "Improve security compliance across your organisation" (sorry I'm terrible at writing this type of copy 🙃)
> The blurb for audit logs could also be more value-oriented. For example: "View and search through a history of all changes made in your Flagsmith organisation". Again, there are probably better ways to word this than what I suggested.

Done

> On self-hosted, instead of linking from the "🔒 Enterprise" badge to https://www.flagsmith.com/contact-us, have we considered linking to https://www.flagsmith.com/pricing? This would be more in line with SaaS where we link to the billing 

It makes sense with the new pricing page yeah, done.


> For change requests, we don't need to mention change requests again in the blurb. It could be shortened to "Add a 4-eyes approval mechanism to your feature changes."

Done

> This PR is also be a good opportunity to remove the SAML plan and flag check here:

image


Not sure what you mean, SAML is enterprise?


> 
> I'm not a fan of the videos to showcase how these gated features work. I understand the intention to quickly show an overview without linking to the docs page, but they're more effort to maintain (the video content itself and how the videos interact with the page layout, which we're not seeing very often during our testing and day-to-day usage) and cannot easily be linked to. I'd prefer to invest in the docs pages and optionally add a secondary action item like "View docs". I also found the videos that display on hover to be jarring/unexpected.

Removed videos 

> Lastly, are there UTM codes we could/should use for any links here to gauge interest on how they're interacted with?
The following event will be tracked for saas
```
{
        'category': 'Locked Feature',
        'event': `View Locked Feature ${feature}`,
      }
```

Enterprise urls will be sent to https://www.flagsmith.com/pricing?utm_source=feature_name
For docs I've added docs.flagsmith.com/bla?utm_source=plan_based_access

**Comment by kyle-ssg** [comment]
> The code looks good, but the multi-factor authentication feature doesn't show a banner when I'm on a free plan.
> 
>  Screen.Recording.2024-07-11.at.12.01.46.PM.mov

Actually, I believe it does but this feature acts differently to others in that it's not organisation specific. If any of your orgs are paid it unlocks it.

image


Also, I've just added this for custom fields.

image

**Comment by rolodato** [comment]
Thanks for the updates! What I meant about SAML is that we're currently hiding the SAML tab entirely from non-Enterprise orgs here: https://github.com/Flagsmith/flagsmith/blob/40bdd5466f1a2aa838ac0dc86b939d5e04cf6605/frontend/web/components/pages/OrganisationSettingsPage.js#L236-L239

For example, a free self-hosted org sees this: 
image

Instead of hiding the SAML tab, we could always show it to all users, but disable the contents of the SAML page depending on the org's plan, in the same way we're disabling features per plan instead of hiding them in this PR.

**Comment by kyle-ssg** [comment]
Ah good catch thanks, added here @rolodato 

image

**Comment by rolodato** [comment]
There's a UI bug here - "Admin Settings" is meant to be a heading, but looks like a toggle switch:

image

This is what is used to look like:

image

I would also remove the `saml_configuration` flag check here, and later delete the flag entirely: https://github.com/Flagsmith/flagsmith/pull/4281/files#diff-670d08164663d0cb284ac1560669dc5f1af2a21b11e0e76178ca0186bbf4bf75R237

We are already recommending all of our customers use this UI section in our docs: https://docs.flagsmith.com/system-administration/authentication/SAML/. Adding another step for self-hosting customers (set up a Flagsmith-on-Flagsmith project and enable this flag) is unnecessary and reduces exposure to this functionality for free self-hosted customers.

**Comment by kyle-ssg** [comment]
@rolodato adjusted

**Review by rolodato — APPROVED** [review]
Great stuff!

**Pull request merged**
