### PR TITLE
feat: Ability to customise default environments for new project

### PR DESCRIPTION
**Pull request by khvn26**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

This PR adds the `default_environment_names_for_new_project` FoF flag to customise default environment names when creating a new project.

## How did you test this code?

Ran the build locally.

### CODE REVIEW

**Review by matthewelwell — COMMENTED** [review]
What was the reason for making this a flag vs an environment variable?

**Review by novakzaballa — COMMENTED** [review]
The code looks good, but for some reason, several tests failed at the same place: `AssertionError: waitForElementVisible([data-test="features-page"])`

**Comment by novakzaballa** [comment]
I ran the e2e tests locally, and they failed.

**Comment by khvn26** [comment]
> What was the reason for making this a flag vs an environment variable?

@matthewelwell I figured this setting is analogous to etc. `segment_operators`.

TBH I'd move all settings to FoF if it was up to me, leveraging the offline mode for static/default values.

**Comment by khvn26** [comment]
@novakzaballa Found the error and fixed it!

**Review by novakzaballa — APPROVED** [review]
Looks good, but I couldn't find the new flag `default_environment_names_for_new_project` in prod.

**Comment by khvn26** [comment]
@novakzaballa The default value will be used for SaaS. The flag is intended for private/self-hosted installations.

**Pull request merged**
