### PR TITLE
chore: diff change requests

### LINKED ISSUE #2191: Add a diff viewer for feature values in change requests
**Is your feature request related to a problem? Please describe.**

When creating a change request for a feature that has a large JSON value, it's hard to see what's changed in the Flagsmith UI. 

**Describe the solution you'd like**

A diff viewer for the value of a feature in a change request. 

**Describe alternatives you've considered**

N/a

**Additional context**

N/a

### PR DESCRIPTION
**Pull request by kyle-ssg**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

Adds feature versioning diff ui to change requests 

## How did you test this code?

- Viewed a change request in production with a value different
image

- Viewed a change request in production with a enabled state different
image

- Viewed a change request in production with a multivariate different
image

### CODE REVIEW

**Comment by matthewelwell** [comment]
When the value is empty and doesn't change, this looks a bit ugly. This is probably the main use case for change requests so I'd like to focus on this not looking like 💩 

image

**Comment by kyle-ssg** [comment]
@matthewelwell This has now been adjusted, features with no value will now hide the value column.

In addition we also can now notify when a change request is exactly the same as live.

image

**Comment by dabeeeenster** [comment]
OK tested the null value and its all good - this can go into prod IMO @kyle-ssg

**Comment by kyle-ssg** [comment]
It's part of a bigger feature versioning branch, will go into that.

**Pull request merged**
