### PR TITLE
Update requirements needed for 3.11

### PR DESCRIPTION
**Pull request by matthewelwell**
## Changes

I had to recreate my local development environment and in the process couldn't install some of the requirements. I think because some older package versions do not have wheels to support 3.11, but I'm not entirely sure why the builds are therefore succeeding. Either way, it seems like a good thing to upgrade these older packages anyway. 

## How did you test this code?

Unit tests.

### CODE REVIEW

**Comment by khvn26** [comment]
google-auth and slack-sdk bumps are huge. We've got to make sure that nothing's broken. I don't suppose e2e covers the relevant scenarios?

**Comment by matthewelwell** [comment]
Yeah, good point. I don't believe the E2E tests cover either of these so we'll need to test these manually. I will try and do this at some point. This PR is not urgent anyway, I'd like to look into why I had to upgrade them in my local environment anyway.

**Comment by gagantrivedi** [comment]
> Yeah, good point. I don't believe the E2E tests cover either of these so we'll need to test these manually. I will try and do this at some point. This PR is not urgent anyway, I'd like to look into why I had to upgrade them in my local environment anyway.

I think because wheel are available for the runner(linux) and not mac OS?

**Comment by khvn26** [comment]
@gagantrivedi I have Python 3.11.3 locally and didn't have to bump any of the requirements.

```sh
➜  ~ sw_vers
ProductName:		macOS
ProductVersion:		13.3.1
BuildVersion:		22E261
```

**Comment by dabeeeenster** [comment]
I've never had any issues with 3.11 either?

**Comment by matthewelwell** [comment]
Yeah, I'm not sure - I'll try creating a new clean environment again to see if I can replicate it. It could possibly have been related to the fact I was using terrible train WiFi at the time...

**Comment by matthewelwell** [comment]
Yep, works fine trying again on stable wifi. I'll close this PR.

**Pull request closed without merging**
