### PR TITLE
feat: Roles management 

### PR DESCRIPTION
**Pull request by novakzaballa**
Thanks for submitting a PR! Please check the boxes below:

- [X] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [X] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [X] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

- Added a "Roles" tab in Manage > Members
- Created a modal for creating and editing roles, along with editing their permissions based on their level (organisation, project, environment)
- Added "show_role_management" flag to wrap this feature.
## How did you test this code?

- Go to manage -> members.
- Click the "Roles" tab.
- Click the "Create Role" button.
- Create a new role.
- Select the role in the role list.
- Edit name and description. (If you want to exit without saving, a confirmation modal will appear.)
- Edit organisation, project, and environment permissions (If you want to exit or change the tab without saving, a confirmation modal will appear.)
- Click the trash button to delete the role.

### CODE REVIEW

**Comment by gagantrivedi** [comment]
@novakzaballa  are you planning to add the code related to adding/removing the user/groups from roles in another PR?

**Comment by novakzaballa** [comment]
> @novakzaballa are you planning to add the code related to adding/removing the user/groups from roles in another PR?

Yes, that will be a new PR.

**Comment by matthewelwell** [comment]
@novakzaballa can you update the description of this PR to detail how you have tested this code.

**Comment by gagantrivedi** [comment]
@novakzaballa is this wrapped in a feature flag?

**Comment by novakzaballa** [comment]
> @novakzaballa is this wrapped in a feature flag?

Yes, the flag is "show_role_management".

**Comment by novakzaballa** [comment]
Closed because there is a complete PR https://github.com/Flagsmith/flagsmith/pull/2791

**Pull request closed without merging**
