### PR TITLE
Update Uffizzi Workflows

### PR DESCRIPTION
**Pull request by ShrutiC-git**
Thanks for submitting a PR! Please check the boxes below:

- [ ] I have run [`pre-commit`](https://docs.flagsmith.com/deployment/locally-api#pre-commit) to check linting
- [X] I have filled in the "Changes" section below?
- [X] I have filled in the "How did you test this code" section below?

## Changes
Changing the two Uffizzi workflows -  `uffizzi-build.yml` and `uffizzi-preview.yml`. These changes will ensure special characters in the PR event will not throw an error while trying to serialize the event into json.

## How did you test this code?

By opening a test PR and making sure the new changes work in creating a new preview environment.

### CODE REVIEW

**Comment by matthewelwell** [comment]
Hey @ShrutiC-git, thanks for this. Could you please rebase / merge latest main into your branch? That should get the 2 failing workflows passing (well, technically they'll be skipped but that's intentional).

**Comment by ShrutiC-git** [comment]
Hey @matthewelwell, thanks for taking a look.
seems the actions are failing post a rebase too, not sure if there might be something else that's missing.

**Comment by matthewelwell** [comment]
Sorry @ShrutiC-git ! Turns out that GH workflows make it harder than it should be (in my opinion) to determine if a PR originated from a forked repository! That should be resolved in main now, could you rebase again please 🙏 ?

**Comment by ShrutiC-git** [comment]
oh, I see, thanks - rebased against the main. I believe this looks good now

**Review by matthewelwell — APPROVED** [review]

**Comment by matthewelwell** [comment]
Thanks @ShrutiC-git

**Pull request merged**
