### PR TITLE
chore: validate chargebee subscription data

### LINKED ISSUE #2372: Add a 'Pull data from Chargebee' button to the sales dashboard
When modifying non-self-serve customer data (seats, plan etc) in Chargebee, it would be helpful to add a button on the organisation's sales dashboard page to pull their data from Chargebee and store an updated copy of that data locally.

### PR DESCRIPTION
**Pull request by dabeeeenster**
Thanks for submitting a PR! Please check the boxes below:

- [X] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

Adds a button that pulls Chargebee subscription data from the Chargebee API, based solely on the Chargebee Subscription ID stored in the `Subscription` object (and submitted in the form) and updates the local databased with the relevant data.

## How did you test this code?

Ran test suite. Added Test Chargebee API key and ran against the test Chargebee instance

### CODE REVIEW

**Comment by dabeeeenster** [comment]
I've fixed the conflicts here as best I can but there's still test errors which I need help with!

**Comment by dabeeeenster** [comment]
Getting errors here. Setting up `.env` to point to Chargebee test account. Then:

1. Create a new Org in chargebee front end
2. Go to sales dashboard and find the org
3. Add the following chargebee sub id: `Azz5iETnxV1Ob28kq`
4. Click "Sync Chargebee Data"

then I get errors:

```django.request ERROR    Internal Server Error: /sales-dashboard/organisations/2
Traceback (most recent call last):
  File "/Users/ben/Library/Caches/pypoetry/virtualenvs/flagsmith-api-acJibsPq-py3.11/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/Library/Caches/pypoetry/virtualenvs/flagsmith-api-acJibsPq-py3.11/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/Library/Caches/pypoetry/virtualenvs/flagsmith-api-acJibsPq-py3.11/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ben/flagsmith/flagsmith/api/sales_dashboard/views.py", line 147, in organisation_info
    subscription_metadata["chargebee_email"] = subscription_metadata.chargebee_email
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
TypeError: 'ChargebeeSubscriptionMetadata' object does not support item assignment
```

**Comment by matthewelwell** [comment]
@dabeeeenster this one is so stale now and seemingly not needed. Going to close and we can reopen if that changes.

**Comment by dabeeeenster** [comment]
OK

**Pull request closed without merging**
