### PR TITLE
fix: Environment creating state

### LINKED ISSUE #4033: "Create Environment" button not disabled during environment creation
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [ ] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

When clicking on "Create Environment", there is no indication of progress or confirmation that the button was clicked, which makes it more likely that users (especially those with high API latency) will click the button more than once.

This bug is particularly annoying because of https://github.com/Flagsmith/flagsmith/issues/4032, which results in multiple environments with the same name being created if the button is clicked multiple times.

### Steps To Reproduce

1. Go to the "Create Environment" page
2. Click on "Create Environment" multiple times quickly
3. Multiple environments with the same name will be created

### Expected behavior

The "Create Environment" button should be disabled during loading. Optionally show some indication of progress that the environment is being created, such as a spinner.

### Screenshots

https://github.com/Flagsmith/flagsmith/assets/829698/d78ea4a4-5ae6-4908-ac7c-20c58d40bb81

image

### PR DESCRIPTION
**Pull request by kyle-ssg**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

Disables create env button when creating

## How did you test this code?

- Created an environment

### CODE REVIEW

**Review by rolodato — APPROVED** [review]
The bug I originally reported is fixed, but we're introducing the same behaviour as in https://github.com/Flagsmith/flagsmith/issues/4026. If the request fails or is blocked, the Create button will never be re-enabled and no error is displayed.

Approving anyway because it's better to need to refresh the page than to delete duplicated environments :)

**Comment by kyle-ssg** [comment]
@rolodato I've fixed the above in the PR

**Comment by rolodato** [comment]
Not sure if I'm looking at the correct deployment, but I can reproduce the same behaviour by blocking the request to clone an environment in https://flagsmith-frontend-staging-4x2teb60z-flagsmith.vercel.app/ :


https://github.com/Flagsmith/flagsmith/assets/829698/61501738-9ce5-4ca0-9c7f-5262f927a1c0

**Comment by kyle-ssg** [comment]
Ah yep I forgot that https://github.com/Flagsmith/flagsmith/pull/4058 is yet to be merged, added the relevant fixes here too.

**Comment by rolodato** [comment]
I see the button correctly being disabled while the environment is being created, but I don't see an error visibly reported if blocking the request or trying to clone an environment while offline:

https://github.com/Flagsmith/flagsmith/assets/829698/b4f634a1-11de-4d17-a49a-7c258142b9e4

**Comment by kyle-ssg** [comment]
Ah yep, spotted the issue here. 

This is now fixed, going to merge as am convinced this works now.

image

**Pull request merged**
