### PR TITLE
chore: Allow manual date entry for scheduling

### LINKED ISSUE #3496: UX Audit - Allow user to type date for scheduling
### Is your feature request related to a problem? Please describe.

I can only schedule changes on the half hour and not more granularly

### Describe the solution you'd like.

Let me type dates/times in the input field

### Describe alternatives you've considered

Add minutes in the dropdown, would be too cumbersome to navigate 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kyle-ssg**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

Allows manual date entry for scheduling, one caveat is that we no longer show the timezone (i.e. their local one), I think this was confusing anyway.

https://github.com/Flagsmith/flagsmith/assets/8608314/dd89f701-5717-40fd-b5e3-6b99c3c4064c

## How did you test this code?

As above

### CODE REVIEW

**Review by novakzaballa — APPROVED** [review]

**Comment by matthewelwell** [comment]
@kyle-ssg the timezone is really important here, I get asked about it every time I show this feature. Can we just add some copy below stating that all times are in the local timezone or something?

**Review by dabeeeenster — APPROVED** [review]

**Comment by kyle-ssg** [comment]
> @kyle-ssg the timezone is really important here, I get asked about it every time I show this feature. Can we just add some copy below stating that all times are in the local timezone or something?

Ok yep, added for when the user selects a future date, I think local time indicates that it'll be live based on the end user's local time (a few people have asked me this) so kept the timezone in the message.

image

**Comment by matthewelwell** [comment]
I still think we can do more here to make it obvious when you're choosing a date. Otherwise we're going to get support questions down the line, I'm sure of it. 

image

Can we just add something to the tooltip for example?

**Comment by kyle-ssg** [comment]
Ok, have added "All dates are displayed in your local timezone." to the tooltip

**Review by matthewelwell — APPROVED** [review]

**Pull request merged**
