### PR TITLE
PR Preview Environments for Enhancing Maintainer Productivity

### PR DESCRIPTION
**Pull request by ShrutiC-git**
Thanks for submitting a PR! Please check the boxes below:

- [X] I have run [`pre-commit`](https://docs.flagsmith.com/deployment/locally-api#pre-commit) to check linting
- [X] I have filled in the "Changes" section below?
- [X] I have filled in the "How did you test this code" section below?

## Description
This PR is adding support for **preview environments for PR events** (opened, sync'ed, reopened, etc) powered by [Uffizzi](https://www.uffizzi.com/). 

The PR uses GHA workflows to build and provision the preview environments. Utilizing docker-compose examples from **Flagsmith's** repo, the PR uses `docker-compose.uffizzi.yml` to build `Flagsmith` from source - this makes sure the latest changes are reflected in the preview. The `docker-compose.uffizzi.yml` also includes a Postgres instance and an Nginx proxy to facilitate mounting other components. 

Once a PR event is triggered — _PR opened, PR synced, review requested_ — the build workflow will build the image, and the preview workflow will either spin up a new preview or update an existing preview. The previews are ephemeral — so they live for only as long as needed. 

A comment will be posted on the PR containing the URL of the preview environment, allowing contributors and maintainers to easily navigate to the preview. 

Fixes - https://github.com/Flagsmith/flagsmith/issues/1738

## Changes
No change has been made in the source of the project for this PR. 

The `docker-compose.uffizzi.yml` file is borrowing major configurations from `docker-compose.yml` in Flagsmith's repo. The `docker-compose.uffizzi.yml` builds 3 different containers:
- **Flagsmith container** (from source, this makes sure the latest changes in the project are reflected in the preview environment)
- **Nginx container** (also exposed as the ingress into the preview environment. The `nginx.conf` file is mounted into the container and this container accepts incoming requests. This will be useful for accessing other UI services, like Influx-dashboard).
- **Postgres container**

The `docker-compose.uffizzi.yml` uses `uffizzi-build.yml` GHA → which is triggered on PR events. Once the build action completes, and the image is built, the `uffizzi-preview.yml` GHA spins up a new preview environment or updates an already existing preview. 

Every new PR will create a fresh preview environment, guaranteeing clean and non-polluted environments for testing changes. 

## How did you test this code?

In order to test this, I have created a [PR](https://github.com/ShrutiC-git/flagsmith/pull/1) against the main branch of my personal fork of `Flagsmith`. This triggered the workflow to create a new preview environment - [here](https://app.uffizzi.com/github.com/ShrutiC-git/flagsmith/pull/1) and this [comment](https://github.com/ShrutiC-git/flagsmith/pull/1#issuecomment-1347781203), posted on the PR, takes me to the preview environment.

The preview is enabled with sign-up. As you will visit the preview environment, you will be able to either sign-up as a new user or alternatively log in. Upon successful sign-in/sign-up, I was taken to the Flagsmith dashboard. Since I signed up as a free user, I was able to play around and test Flagsmith as a free user — and quite literally had more flags than the UN!

***********

An in-depth study on preview environments can be found [here](https://www.uffizzi.com/preview-environments-guide). Here is another easy read on [where can you use Uffizzi](https://docs.uffizzi.com/use-cases/why-uffizzi/#what-can-i-use-uffizzi-for).

Looking forward to powering preview environments for Flagsmith, and thereby, making reviewing, testing, releasing easy. Please do suggest improvements, ask questions, and/or send along concerns - it will help Uffizzi better align with Flagsmith! 

cc @dabeeeenster @waveywaves

### CODE REVIEW

**Comment by dabeeeenster** [comment]
`Deploy Uffizzi Preview` workflow action doesnt seem to be called?

**Comment by ShrutiC-git** [comment]
hey there, @dabeeeenster , that's a good question. Perhaps, I'll also update the description to address this.

The reason the `Deploy Preview Action` did not run for this PR is because it is a workflow run, dependent upon the previous workflow — `Build New Preview`. For the `Deploy Preview Action` to be triggered there are 2 conditions:
- The `Build New Preview` action must be completed (we deploy the artifact from this step)
- This workflow file must be present in the default branch of the repo. 

In my PR, my default branch is `uffizzi`, and the `Deploy New Preview` workflow file is in the default branch. Any PR, in this case, would trigger the `Deploy New Preview` action. 

Once the PR is merged into the default branch of this repo, you will also see the `Deploy New Preview` triggered. 

[Here are the docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run) on `workflow run`.

**Comment by dabeeeenster** [comment]
Ah ok understood thanks - and once the action runs will it report the URLs of the PR instances on the uffizzi side? I'm just concious that I still havent created an account on that side.

**Comment by ShrutiC-git** [comment]
@dabeeeenster ~
the `deploy new preview` action will pin a comment to the PR. This comment will have a public URL of the preview, open to all (you can also configure password-protected previews). 

The comment will be pinned to the PR directly without needing any additional effort from your end! It is handled by the `Deploy Preview` action.

[Here is an example](https://github.com/ShrutiC-git/flagsmith/pull/1#issuecomment-1347781203) of what that comment looks like. Let me know if that answers your question!

**Comment by matthewelwell** [comment]
@ShrutiC-git thanks for this! 

I've had a look over the PR and it looks good but I find the workflows are quite complex. Because of this, I'm a little concerned we won't be able to maintain them ourselves if we need to in the future! 

I'm also a little confused as you mentioned [here](https://github.com/Flagsmith/flagsmith/issues/1738) that Uffizzi is completely free for open source projects, however, when I click on the 'Application Logs etc.' link in the comment that you linked to above, it shows me a paywall.

**Comment by ShrutiC-git** [comment]
hi @matthewelwell, thanks for posting your concerns. 

Re the workflows being complex - with Uffizzi, we are trying to make the integration and maintenance as easy as possible for maintainers. And the first step in that is ensuring that the Uffizzi community is always available for help. That is our effort. Since we are open-sourced, we follow the culture of keeping the community first and regular follow-ups with projects. 

If it'd be helpful for Flagsmith, we can also set up a call to go through the technical details and also answer any other concerns. A walkthrough of the workflows will be helpful. We are also working on publishing a guide to the `2-stage-workflow`, as we call it. I can see where we are with that, and I'll send it along your way — that will also provide context and will be helpful. 

Re the paywall — good catch. You're right, we're free for open-source projects. Once Flagsmith is onboarded with us (and that would mean merging this PR), you will not see the paywall anymore! If you want, I can see what arrangements we can make so you can test that feature out as well. We can also discuss this in a call if you'd like and maybe also take a look at the logging capabilities.

Thanks so much for bringing this to my attention.

**Comment by matthewelwell** [comment]
@ShrutiC-git, ok, thanks let's merge it and then see if we need a call to go through anything in the future.

**Review by matthewelwell — APPROVED** [review]

**Comment by ShrutiC-git** [comment]
sounds good, @matthewelwell, thank you. Yes, please do reach out with any questions or concerns. Here is my email - shruti.chaturvedi@uffizzi.com

We also have a Slack community, this will be a good place to get in touch with us, and other teams, using Uffizzi, ask questions, and provide feedback - [here is the invite](https://join.slack.com/t/uffizzi/shared_invite/zt-1l3g14kh3-7RlOyAtauOEQhHh9y0K3kg)

Meanwhile, I will intimate our team to remove the paywall! I'll let you know once it's lifted ~

**Comment by matthewelwell** [comment]
Thanks @ShrutiC-git. It looks like the 'Deploy Uffizzi Preview' workflow failed when I merged this PR into main - are you able to explain why? It looks like it failed deleting the build - perhaps that's because one wasn't created for _this_ PR? 

Here is the failed job: https://github.com/Flagsmith/flagsmith/actions/runs/3694549599/jobs/6255873837

**Comment by ShrutiC-git** [comment]
hey @matthewelwell, looked into this ~ yes, this failed because there wasn't a build that was created for this PR.
on closing the PR, the `delete environment action` under the `uffizzi-build` flow is triggered. The delete-environment step was the first step that ran in this repo after the PR was merged (https://github.com/Flagsmith/flagsmith/actions/runs/3694547475). 

Since at this time, there were no active builds -(https://github.com/Flagsmith/flagsmith/actions/runs/3694549599/jobs/6255873837#step:8:64)-  GHA threw this error. 

This is a good catch, we should have better error handling for these cases, thank you.

Let me open a test PR and check if everything is working alright.

**Comment by ShrutiC-git** [comment]
@matthewelwell 
here is the _build for the test PR I opened_ (new preview deployed) - https://github.com/Flagsmith/flagsmith/actions/runs/3695088930

and this is the _deploy preview for this run_ - https://github.com/Flagsmith/flagsmith/actions/runs/3695114167

and this is the comment posted for this PR - https://github.com/Flagsmith/flagsmith/pull/1770#issuecomment-1351330392

I'll close this PR in a few minutes after you look into it / we can check if the preview will successfully delete

**Comment by ShrutiC-git** [comment]
The paywall should be lifted too, @matthewelwell - let me know if you can access the logs. Before you do that, could you please check the point below -

could you also please sign up with GitHub with us? You were seeing the paywall because you signed up with your email. With email sign-ups, it is hard to track which GH org an account belongs to. Signing up with GitHub will add you as a member of Flagsmith - and you will no longer be seeing the paywall issues you were seeing earlier with your email signup.

**Comment by jpthurman** [comment]
hi @matthewelwell - I work with @ShrutiC-git.  Jumping in for a clarification.  When you go to sign-in to Uffizzi please sign-in with Github - this is how we automatically connect you to your Org account that was created when you accepted the PR.

**Comment by matthewelwell** [comment]
Ah, ok, that makes sense. The reason I opted not to sign up with Github, however, is because of this: 

Screenshot 2022-12-14 at 14 56 23

Can you explain to me why you need access to act on my behalf?

**Comment by gadkins** [comment]
Hi @matthewelwell. I'm Grayson, Co-founder at Uffizzi. I'm happy to address the screenshot above.

The short answer is that this is part of the standard permissions for GitHub OAuth. The warning is misleading because Uffizzi is only requesting read-only access to your email address and username at this step to set up your account. Other projects using GitHub OAuth have had the same issue as you can see [here](https://github.com/vercel/platforms/discussions/79) and [here](https://github.com/cirruslabs/cirrus-ci-docs/issues/751). In fact, a GitHub staffer has even acknowledged the confusing wording and that it may change, as described [here](https://github.com/community/community/discussions/37117#discussioncomment-3973136).

After selecting **Authorize Uffizzi Cloud,** you are asked to **Install & Authorize** the Uffizzi GitHub App, where you can see which permissions Uffizzi is requesting. Uffizzi requests only the minimum permissions it needs. The only way Uffizzi acts on your behalf is by commenting on PRs. See screenshot below.

We will be adding this information to our documentation to avoid confusion. Also you can read more about authorizing GitHub Apps [here](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/authorizing-github-apps).

Screen Shot 2022-12-14 at 11 16 54 AM

Cc @ShrutiC-git

**Comment by ShrutiC-git** [comment]
thank you for raising a very valid concern re permissions. We will definitely address this in our documentation. 

I'm also closing [Test PR #1](https://github.com/Flagsmith/flagsmith/pull/1770) to trigger the `Delete Preview` step and see if it's behaving as it should~

update - the preview was deleted successfully, [here](https://github.com/Flagsmith/flagsmith/actions/runs/3701227678/jobs/6270357482#step:11:15) is the corresponding workflow run

**Comment by gadkins** [comment]
Also, you can read more about why we use two workflows [here](https://www.uffizzi.com/preview-environments-guide/github-actions-two-stage-workflow).

**Pull request merged**
