### PR TITLE
changes some code to mandatory to write description in new feature

### PR DESCRIPTION
**Pull request by jatingodnani**
Thanks for submitting a PR! Please check the boxes below:

- [ -] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [- ] I have filled in the "Changes" section below?
- [ -] I have filled in the "How did you test this code" section below?
- [ -] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

#2873 

_Please describe._

=>changes some code to mandatory to fill the description
## How did you test this code?

=>in localhost:8080

### CODE REVIEW

**Review by matthewelwell — CHANGES_REQUESTED** [review]
@jatingodnani this does not meet the requirements at all. You'll need to add some changes to the ORM such that the description can be made optional only for certain projects. The changes you have added make the description a required field (in the UI only) for all projects.

**Comment by jatingodnani** [comment]
@matthewelwell ok,my question is which type of project require optional field.if you can give me more detail then it will easy to understand

**Comment by jatingodnani** [comment]
You can tell me the min length of description

**Comment by matthewelwell** [comment]
That's for the user to define. To make this generic enough so we can use it for multiple fields on different objects, controlled by different parent objects, I am imagining we ideally want something like: 

```python
class RequiredField(Model):
    parent_object_content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    parent_object_id = GenericObjectID()
    child_object_content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    field_name = models.CharField(max_length=200)
```

This would allow us to, for example, configure that the `description` field is required for all features in a given project but it will also allow us to, for example, say that the `description` field is required for all segments in a given project too.

This is quite complex django logic, however, so let me know if this is not in your wheelhouse. 

A slightly simpler (but acceptable) solution that will likely cover all the use cases I can think of is to link it directly to a project only. That way the model becomes more like: 

```python
class ProjectEntityRequiredField(AbstractBaseExportableModel):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="required_fields_for_child_entitites")
    child_object_content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    field_name = models.CharField(max_length=200)
```

Then, to enforce that the description field is required on the Feature model for a given project, you would need to do something like: 

```python
feature_content_type = ContentType.objects.get(app_label="features", model="feature")
project = Project.objects.get(name="my-project")
ProjectEntityRequiredField.objects.create(project=some_project, child_object_content_type=feature_content_type, field_name="description")
```

and to use that data in the validation, you can just do something like this:

```python
project = Project.objects.get(name="my-project")
required_fields = project.required_fields_for_child_entitites.filter(child_object_content_type__model="feature").all().values_list("field_name", flat=True)
```

**Comment by jatingodnani** [comment]
@matthewelwell if this is form certain project,then i think 
It should be kept as optional

**Comment by matthewelwell** [comment]
@jatingodnani the requirement is to make it required for certain projects. If you're not comfortable implementing this, please close the PR and we will reassign the issue in Github.

**Comment by jatingodnani** [comment]
@matthewelwell thankyou for response.i dont know django and i am closing this pr

**Pull request closed without merging**
