### PR TITLE
style: Login / signup

### PR DESCRIPTION
**Pull request by kyle-ssg**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

image

image

image

## How did you test this code?

_Please describe._

### CODE REVIEW

**Comment by matthewelwell** [comment]
Tested this via the vercel preview in staging... I can't get to the login form. 

https://github.com/Flagsmith/flagsmith/assets/14089968/65e844da-0c4f-434b-aa91-a55caed17179

**Comment by matthewelwell** [comment]
Seems like there is some issue with dark mode bleeding into the login form. To reproduce:

 1. Login
 2. Set the application into dark mode
 3. Log out

You should see the following spawn of hell login form

image

**Comment by matthewelwell** [comment]
Now I just see a blank screen on log out? 

https://github.com/Flagsmith/flagsmith/assets/14089968/df4af47c-25b6-41f8-83c2-73e6907f99ed

**Comment by kyle-ssg** [comment]
@matthewelwell should be sorted now

**Comment by matthewelwell** [comment]
> @matthewelwell should be sorted now

Looks good now, yep. Thanks!

**Review by matthewelwell — APPROVED** [review]

**Pull request merged**
