### PR TITLE
chore: test trimmed value when determining type

### LINKED ISSUE #4041: Feature or segment override value data type is determined before whitespace trimming
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [X] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

When changing a feature value or a segment override, Flagsmith tries to automatically detect its data type (i.e. string, boolean, number) by looking at specific values such as `true`, `True`, `false`, etc (some fields omitted for brevity):

```json
{
  "id": 95055,
  "name": "my_boolean_feature",
  "type": "STANDARD",
  "default_enabled": false,
  "initial_value": "true",
  "project": 16945,
  "environment_feature_state": {
    "id": 536035,
    "feature_state_value": true,
    "environment": 44251,
    "identity": null,
    "feature_segment": null,
    "enabled": false
  }
}
```

In comparison, string features are returned as JSON strings:

```json
{
  "id": 95057,
  "name": "my_string_feature",
  "type": "STANDARD",
  "default_enabled": false,
  "initial_value": "Hello world!",
  "project": 16945,
  "environment_feature_state": {
    "id": 536047,
    "feature_state_value": "Hello world!",
    "environment": 44251,
    "identity": null,
    "feature_segment": null,
    "enabled": false
  }
}
```

However, it's possible to get into a state where a value of `true` is returned as a string:

```json
{
  "id": 95059,
  "name": "my_not_boolean_feature",
  "type": "STANDARD",
  "default_enabled": false,
  "initial_value": "true",
  "project": 16945,
  "environment_feature_state": {
    "id": 536063,
    "feature_state_value": "true",
    "environment": 44251,
    "identity": null,
    "feature_segment": null,
    "enabled": false
  },
  "num_segment_overrides": 0,
  "num_identity_overrides": null,
  "is_server_key_only": false,
  "last_modified_in_any_environment": "2024-05-29T12:32:40.620691+00:00",
  "last_modified_in_current_environment": null,
  "metadata": []
}
```

This can cause applications that depend on this data type to break.

This is the payload sent to `PUT https://api.flagsmith.com/api/v1/environments/{environment}/featurestates/{featurestate}/` when updating the feature value to have leading whitespace:

```json
{
  "id": 536063,
  "feature_state_value": " true",
  "multivariate_feature_state_values": [],
  "identity": null,
  "deleted_at": null,
  "uuid": "1fb16538-80eb-40bb-98fe-1f972245a01c",
  "enabled": false,
  "created_at": "2024-05-29T12:32:40.491733Z",
  "updated_at": "2024-05-29T12:33:07.637304Z",
  "live_from": "2024-05-29T12:32:40.489748Z",
  "version": 1,
  "feature": 95059,
  "environment": 44251,
  "feature_segment": null,
  "change_request": null,
  "environment_feature_version": null
}
```

Similarly, this is the payload sent to `PUT https://api.flagsmith.com/api/v1/features/featurestates/{featurestate}/` when creating a segment override:

```json
{
  "id": 536086,
  "feature_state_value": {
    "boolean_value": null,
    "integer_value": null,
    "string_value": "true ",
    "type": "unicode"
  },
  "multivariate_feature_state_values": [],
  "deleted_at": null,
  "uuid": "ed6d42bc-3495-49bf-a5f4-29cf1730a15e",
  "enabled": false,
  "created_at": "2024-05-29T12:47:00.570145Z",
  "updated_at": "2024-05-29T12:47:02.504254Z",
  "live_from": "2024-05-29T12:47:00.567710Z",
  "version": 1,
  "feature": 95059,
  "environment": 44251,
  "identity": null,
  "feature_segment": 63719,
  "change_request": null,
  "environment_feature_version": null
}
```

The trailing whitespace is not returned by Flagsmith when requesting the feature state or segment override.

A possible workaround would be to use the boolean state of the feature and not its value, but this does help customers using the "Hide disabled flags from SDKs" setting.

### Steps To Reproduce

1. Create a feature with a value (not boolean state) of `true`
2. Add whitespace before or after the value, such as `true ` or ` true`
3. Save changes

The feature will now have a string value of `"true"` and ignore the leading whitespace.

This is what the change looks like in the audit log:

image

### Expected behavior

Feature or segment override values with leading and/or trailing whitespace, such as ` true ` or `false ` should always be stored as booleans. In other words, the data type of a value should be determined after trimming spaces, and not before.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by kyle-ssg**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

When saving a feature state, the frontend will now attempt to trim the value to detect boolean/int/float. If it parses a value it'll use that.

For example, editing remote config with `" true"` will now send the following 

image

It's important the frontend only does this when determining data to send to the API so that typing new values doesn't prevent spaces.

### CODE REVIEW

**Comment by rolodato** [comment]
@kyle-ssg This still isn't working for me - I can turn a boolean `true` into `"true"` by adding leading or trailing spaces:

https://github.com/Flagsmith/flagsmith/assets/829698/9c44bedf-7052-4f56-8a20-28a3172da05b

**Comment by kyle-ssg** [comment]
@rolodato after discussing further I believe this is fixed, this should also be tested for Multivariate (A/B) values too

**Comment by rolodato** [comment]
I'm still testing everything else but I've noticed a regression that I'm unable to reproduce in production - focusing and then unfocusing a variation value on a multivariate feature will mark the feature as modified, even if no whitespace is being trimmed:

https://github.com/Flagsmith/flagsmith/assets/829698/0c3d5338-b625-481e-a41e-f6c3df5b15cf

**Comment by rolodato** [comment]
I can also save a feature value of `"true "` by creating an identity override:

https://github.com/Flagsmith/flagsmith/assets/829698/11c5158f-df10-4bdc-bb98-e21bc72f33b7

**Comment by kyle-ssg** [comment]
@rolodato should be sorted on next build, thanks for the thorough check

**Review by rolodato — APPROVED** [review]

**Pull request merged**
