### PR TITLE
fix: save feature error handling

### LINKED ISSUE #4026: "Save" button in modals is never re-enabled in case of failure
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [X] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

When saving changes within a modal (i.e. feature states, segments, segment overrides, possibly others), the Save button is disabled while requests are still pending. However, if a request fails, the button is never re-enabled and requires a page reload to be clickable again. This effectively means losing all your UI state, which can be very frustrating.

### Steps To Reproduce

See video below.

1. Force a request initiated by saving within a modal to fail somehow. For example, manually block a request needed to save a feature using developer tools:

image

2. Save a feature, forcing a request to be blocked
3. The Save button is never re-enabled and requires a full page reload to work again

### Expected behavior

Saving within modals should have proper error handling and eventually always re-enable the Save button.

The error message should be displayed to the user, requiring manual dismissing to allow time to copy/paste or screenshot the error.

### Screenshots

https://github.com/Flagsmith/flagsmith/assets/829698/a352a287-ed4f-4ac7-a989-bef9122a6fa6

### PR DESCRIPTION
**Pull request by kyle-ssg**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

Tracks and displays errors when saving a feature.

## How did you test this code?

- Created a feature with a duplicate name 
- Attempted to save a feature whilst offline

### CODE REVIEW

**Comment by rolodato** [comment]
I'm still able to reproduce https://github.com/Flagsmith/flagsmith/issues/4025 on this preview environment:


https://github.com/Flagsmith/flagsmith/assets/829698/ad625a1e-abb9-45b7-afad-65dbac56b2a2

(#4025 is about the 404 error, this issue is about the error not being displayed and the save button not being re-enabled after an error)

**Comment by kyle-ssg** [comment]
Thats just because the PR doesnt have the latest main, the PRs were all up at the same time.

The preview url will now contain the other changes from yesterday.

**Comment by kyle-ssg** [comment]
@rolodato This can be re-tested

**Comment by rolodato** [comment]
Tested again, this works:

* Creating a feature with a duplicate name
* Updating a feature twice on a versioning v2 environment, without closing the modal

This doesn't work:

* Creating a feature while offline - no error message is shown and the Create button is never re-enabled
* Updating a feature while offline - same as above

https://github.com/Flagsmith/flagsmith/assets/829698/e17729f6-0ab4-4a12-92e4-e20c76d89756

**Comment by kyle-ssg** [comment]
@rolodato can I just check you're testing on the right url ? Strangely the url in your video doesn't have the branch name in it.

Failing that, I suppose it could be that your browser is retrying/trying to connect the request whilst offline in which case I can't intercept it.


Regardless, here's what I'm seeing on the above.

https://github.com/Flagsmith/flagsmith/assets/8608314/00b5da8b-649f-4415-b061-af6ce8a0d61b

**Comment by rolodato** [comment]
@kyle-ssg I tried visiting the preview URL from your video (https://flagsmith-frontend-preview-git-fix-save-featur-1e23c8-flagsmith.vercel.app) and I still get the same behaviour when trying to create a feature in Firefox with "Work Offline" enabled, or in Chromium when setting the devtools Network throttling mode to "Offline". I see the same `ERR_INTERNET_DISCONNECTED` errors as you, but in my case no error is shown in the UI and the "Create Feature" or "Update Feature" buttons are never re-enabled.

Digging deeper I've found why this is working for you - you're trying to update a feature in a versioning-v1 environment. This also shows an error for me as expected. However, these all fail with no error message and the buttons are never re-enabled:

* Create a feature in a v1 environment
* Create a feature in a v2 environment
* Update a feature in a v2 environment

Hopefully this video makes it clearer:

https://github.com/Flagsmith/flagsmith/assets/829698/34d180a0-4f12-4be4-9aed-81b4670c3c75

**Comment by rolodato** [comment]
@kyle-ssg were you able to take a look at my comment above?

**Comment by kyle-ssg** [comment]
Should be resolved @rolodato , I believe this was only fixed for non-versioned environments before.

**Review by novakzaballa — COMMENTED** [review]
No error is displayed when attempting to create a new feature offline, all other cases appear covered.

**Comment by rolodato** [comment]
Updating works with or without feature versioning, but I get the same behaviour (create button never re-enabled) when creating features on your latest changes.

**Comment by kyle-ssg** [comment]
@rolodato I've added error handling for create flag

**Comment by kyle-ssg** [comment]
Going to merge this, any follow up issues can be a separate ticket.

**Comment by rolodato** [comment]
@kyle-ssg apologies for the late reply - I do see an error when trying to create a duplicate feature now, but the error message shown is `[object Object]`:

image

Looking at https://flagsmith-frontend-staging-git-fix-save-featur-5a4f48-flagsmith.vercel.app/project/6111/environment/apzb2ZhCSF5jcfC7udhnLB/features

**Comment by kyle-ssg** [comment]
@rolodato I promise this is the last time 😄

**Review by rolodato — APPROVED** [review]
Approved - found one more preexisting bug if you'd like to fix it in this same PR:

1. Try to create a feature with a duplicate name, get an error
2. Close the "new feature" modal
3. Edit any feature - the error from step 1 is shown here


https://github.com/user-attachments/assets/710bf07b-f0ae-401b-9020-a6d150ee3415

**Pull request merged**
