### PR TITLE
feat: Add use_identity_overrides_in_local_eval setting

### LINKED ISSUE #4607: UI(environment): Add toggle for use_identity_override_in_local_eval

### PR DESCRIPTION
**Pull request by kyle-ssg**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

image

## How did you test this code?
Toggled setting

### CODE REVIEW

**Review by rolodato — APPROVED** [review]
image

image

Other than that looks good, but I'd like to have some explanation on why users would want to have this enabled or not. There are also docs like https://docs.flagsmith.com/clients/#local-evaluation-1 that need to be updated to take into account this new setting, but we can add this in a different PR

**Comment by kyle-ssg** [comment]
Good question as to why they'd want this enabled or not, I get the feeling that we'd start enabling this by default @gagantrivedi ? 

The only reason I see this being useful as an option is if a project uses flags on the backend and frontend and want to reserve identity overrides for just development and never want it hitting their backend.

**Comment by gagantrivedi** [comment]
> Good question as to why they'd want this enabled or not, I get the feeling that we'd start enabling this by default @gagantrivedi ?
> 
> The only reason I see this being useful as an option is if a project uses flags on the backend and frontend and want to reserve identity overrides for just development and never want it hitting their backend.


The reasoning is captured here https://flagsmith.slack.com/archives/CTF0THS2D/p1725270568904189?thread_ts=1724865246.072169&cid=CTF0THS2D

**Review by gagantrivedi — APPROVED** [review]

**Comment by kyle-ssg** [comment]
Ok yep, bringing here for visibility 

> This will mean that a release on our side might (probably will) change the value for flags in our customer’s environments. I actually think this should be an opt in flag on the environment, defaulted to true for all new environments, but off for any 
 existing ones.

So essentially this is to avoid any unexpected changes

**Comment by kyle-ssg** [comment]
@rolodato based on this, should we just have a small note somewhere on this rather than having it be too prominent in docs ?

**Comment by rolodato** [comment]
Let's merge this as-is and improve the docs later. Getting more people onboarded to this is more important than having perfect docs.

We'd need to share more detailed context in the docs by explaining that this is only for SaaS, was/will be enabled by default for all new environments since a specific Flagsmith version - too much to fit in a small note IMO.

**Pull request merged**
