### PR TITLE
docs: upgrade docusaurus to v3

### LINKED ISSUE #3201: Upgrade docs/docusaurus to node 20

### PR DESCRIPTION
**Pull request by dabeeeenster**
- Migrate to Docusuarus v3
- Migrate to redoc for API documentation built on OpenAPI docs

### CODE REVIEW

**Comment by matthewelwell** [comment]
The API docs are totally broken here. 

Screenshot 2023-12-05 at 14 17 24

**Review by matthewelwell — DISMISSED** [review]
See comment on main PR thread!

**Comment by dabeeeenster** [comment]
OK this is fixed

**Comment by dabeeeenster** [comment]
This can wait till after the Identity Overrides

**Comment by matthewelwell** [comment]
Some remaining issues: 

### Page title

image

### `feature_state_value` is missing. 

**Old**: 

image

**New**:

image

### No idea what these buttons do (seemingly nothing!)

Screenshot 2023-12-12 at 17 25 57

### These are kinda odd. Not sure if they're a design feature, but they're hiding the array brackets making it less obvious that the return is an array. 

Screenshot 2023-12-12 at 17 28 05

**Comment by dabeeeenster** [comment]
OK all these are fixed bar the styling change - think docusaurus and redoc are fighting - not sure we care that much? Might be a bit of a CSS rabit hole as theres a LOT of react magic going on...

**Comment by matthewelwell** [comment]
Yep, the styling issue I can get over. This is important though: 

image

Feature state value is _not_ a string. This is what we had previously: 

image

**Comment by dabeeeenster** [comment]
OK thats fixed

**Review by matthewelwell — APPROVED** [review]

**Pull request merged**
