### PR TITLE
feat: Surface password requirements on signup / dynamic validation

### PR DESCRIPTION
**Pull request by sumtzehern**
Thanks for submitting a PR! Please check the boxes below:

- [X] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [ ] I have added information to `docs/` if required so people know about the feature!
- [X] I have filled in the "Changes" section below?
- [X] I have filled in the "How did you test this code" section below?
- [X] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

Added a PasswordRequirements component to the signup form to provide real-time feedback on password requirements.

## How did you test this code?

I tested this code by:
1. Running the application locally.
2. Navigating to the signup form.
3. Entering different passwords to verify the real-time feedback for password requirements.
4. Ensuring all password requirement checks (length, number, special character, uppercase, and lowercase letters) work as expected.

### CODE REVIEW

**Comment by kyle-ssg** [comment]
@sumtzehern, Aesthetically this is awesome! However it looks like I was able to sign up with the following.

Discussing internally, the requirements do look sensible either way - could we adjust the PR to disable the button whilst they aren't met? Also as the image indicates, the symbol check needs adjusting.

Also maybe if you could try replacing the x and check with ionicons 


```
import { close, checkmark } from 'ionicons/icons'
import { IonIcon } from '@ionic/react'
```

image

**Comment by sumtzehern** [comment]
@kyle-ssg, made some changes including:

1. Replaced x and check icons with Ionicons.
2. Adjusted password validation to include more symbols.
3. Disabled 'Create Account' button until requirements are met.

Screenshot 2024-07-12 at 1 49 30 PM

**Comment by kyle-ssg** [comment]
Thanks so much, this looks great!

**Review by kyle-ssg — APPROVED** [review]

**Comment by sumtzehern** [comment]
@kyle-ssg, Awesome, Good to know

**Pull request merged**
