### PR TITLE
feat: versioned feature states

### PR DESCRIPTION
**Pull request by kyle-ssg**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

- Opt into feature state versioning via environment settings
- Create versioned segment overrides, environment feature state updates and multivariate options

What this does not fully cover, this should follow in an upcoming PR

- Change Requests workflow for versioning
- Creating/Deleting Multiviariate options

## How did you test this code?

- e2e tests that go through creating tests with feature versions enabled to check for regression

- Created and updated feature state remote config
image

- Updated feature enabled state
image

- Created a segment override
image

- Update segment override
Note: there is currently an API issue @matthewelwell is looking into.

- Update multivariate weightings
Note: this will probably change in the future, different feature versions could technically have totally different multivariate options, this currently only diffs the options that exist in the live feature.

image

### CODE REVIEW

**Review by novakzaballa — APPROVED** [review]
The code looks good to me, I didn't have the time to make functional tests, should I?

**Comment by matthewelwell** [comment]
This is blocked waiting for a full manual E2E test (currently sitting with me).

**Comment by dabeeeenster** [comment]
image

Some FE tweaks required here @kyle-ssg

**Comment by dabeeeenster** [comment]
1. Create a flag without a config value
2. Toggle the flag
3. Add a config text value
4. View the version history of that flag and select Compare
5. Hit this console error and entire app crashes/whitescreens.

image

**Review by zachaysan — COMMENTED** [review]
1. Have an enabled feature with a single segment
2. Change the integer value for the feature
3. Go to the history screen.
4. Click compare for the live feature
5. It whitescreens with the below console log

image


image

**Review by zachaysan — COMMENTED** [review]
1. Enable feature versioning settings for "Production" environment and see feature history list.
2. Switch to "Development" environment.
3. Click on feature history button.
4. Shown below error. If scaleup is required then the first environment shouldn't have been enabled. On the other hand if scaleup isn't required then a different message should be displayed when feature versioning isn't enabled for an environment.
image

**Comment by kyle-ssg** [comment]
> 1. Enable feature versioning settings for "Production" environment and see feature history list.
> 2. Switch to "Development" environment.
> 3. Click on feature history button.
> 4. Shown below error. If scaleup is required then the first environment shouldn't have been enabled. On the other hand if scaleup isn't required then a different message should be displayed when feature versioning isn't enabled for an environment.
> 
> image

This is expected, envionments that don't have versioning enabled will be sent to the audit log page.

Edit: after discussion, it was decided that it's better to separate audit log and history actions, you can now do either of these.

**Comment by kyle-ssg** [comment]
Above issues are resolved.

**Comment by dabeeeenster** [comment]
OK yep my issues are fixed. Is there anything else blocking this going live?

**Review by zachaysan — COMMENTED** [review]
My issues have been addressed.

**Comment by matthewelwell** [comment]
> OK yep my issues are fixed. Is there anything else blocking this going live?

Well, yes - this

image

@kyle-ssg 

(but I love that we have new E2E tests here!)

**Comment by kyle-ssg** [comment]
My bad, was just a duplicate data-test attribute added from [latest feedback](https://github.com/Flagsmith/flagsmith/pull/2688/commits/ea60a95b3181b53d04695302cb21af5a472fdda7) to split audit log links from versioning links. I think we're good to go when tests pass.

**Pull request merged**
