### PR TITLE
Add Azure Application insights integration via OpenCensus

### PR DESCRIPTION
**Pull request by veselfil**
Adds support for sending telemetry into Azure Application Insights via the OpenCensus SDK.

Microsoft docs: https://docs.microsoft.com/en-gb/azure/azure-monitor/app/opencensus-python

### CODE REVIEW

**Comment by dabeeeenster** [comment]
Hey thanks so much for this! Are you able to run the pre-commit black formatting across the changes to fix these failing builds?

**Comment by veselfil** [comment]
Yep, updated.

**Review by matthewelwell — APPROVED** [review]

**Comment by veselfil** [comment]
Just FYI OpenCensus should also support DB instrumentation, however from what I managed to find out, it only works with synchronous workers(?) due to the way it [registers the callback](https://github.com/census-instrumentation/opencensus-python/blob/c16e3241261f09bb91b442e9002e897a36d865f2/contrib/opencensus-ext-django/opencensus/ext/django/middleware.py#L174).

We managed to get it to work by following [Django docs](https://docs.djangoproject.com/en/4.0/topics/db/instrumentation/) and adding a custom middleware. We can create a PR for that as well if you're interested.

**Comment by matthewelwell** [comment]
Thanks @veselfil !

**Pull request merged**
