### PR TITLE
Improve audit page loading

### LINKED ISSUE #1993: Audit log paging is slow and feels broken
1. The audit log generally on first load is slow - maybe an API issue?
2. The paging feels broken due to 1. But we should maybe show a spinner when waiting for a page of results
3. I'm not sure if when turning off/on a filter the list is showing the first page or not? Seems like its not? 

gz#490

### PR DESCRIPTION
**Pull request by kyle-ssg**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/deployment/locally-api#pre-commit) to check linting
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?

## Changes

Page request will revert back to 1 when the environment changes, audit list will now indicate it's loading a new page.

image

### CODE REVIEW

**Comment by dabeeeenster** [comment]
@kyle-ssg can we include page number somewhere too? Would be helpful

**Comment by kyle-ssg** [comment]
I'll take a look at keeping that state. Edge paging doesn't bring back that info.

**Comment by kyle-ssg** [comment]
Added

**Comment by matthewelwell** [comment]
> I'll take a look at keeping that state. Edge paging doesn't bring back that info.

This isn't touching edge though so you shouldn't have to keep the state here? On this endpoint you should be able to display how many pages, etc. there are as all the data you need is available to you. The only endpoint that it's not available on is the `/environments/:key/edge-identities/` endpoint. 

This is fine for now, but it would probably be nice to have a view of how many pages there are.

**Comment by kyle-ssg** [comment]
Ok yeah I can see a count have adjusted to use that to calculate the current page

**Review by matthewelwell — APPROVED** [review]

**Pull request merged**
