### PR TITLE
style: feature filters and compact mode

### PR DESCRIPTION
**Pull request by kyle-ssg**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

- Feature table filters
- Compact mode (Applying some suggestions in https://github.com/Flagsmith/flagsmith/pull/2981)
- Improve create tag ui
- Fix border radius issue on tables

**Feature table filters**

image

image

image

**Compact view**
image

This PR also lead me to believe that the create/edit tag flow is inconsistent with the rest of the design.

**Before**

**After**

This PR also fixes a slight issue where the border on tables is not rendered correctly

image

## How did you test this code?

- Viewed/filtered features on the features page and user page.

### CODE REVIEW

**Comment by dabeeeenster** [comment]
I think we just need to add owners filtering (both users and groups) here?

**Comment by kyle-ssg** [comment]
@dabeeeenster would need API work, I think we should have feature parity then do that as a separate ticket.

**Comment by dabeeeenster** [comment]
> @dabeeeenster would need API work, I think we should have feature parity then do that as a separate ticket.

OK sounds good

**Review by novakzaballa — APPROVED** [review]
Approved! Just a quick note: could you remove the `console.log('isloading', isLoading)` for cleaner code?

**Pull request merged**
