### PR TITLE
docs: Getting flags by identity - iOS

### PR DESCRIPTION
**Pull request by jackforesightmobile**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

Add documentation and code examples to the iOS docs for getting flags by an identity.

### CODE REVIEW

**Comment by dabeeeenster** [comment]
Can we include some Traits in here too?

**Comment by jackforesightmobile** [comment]
> Can we include some Traits in here too?

Traits are already in there just above @dabeeeenster 
image

**Comment by matthewelwell** [comment]
@jackforesightmobile I think Ben is asking whether we can show that you can set traits when requesting the flags for an identity as this is the case in most of our SDKs. I'm not sure if that's the case here?

**Comment by dabeeeenster** [comment]
> @jackforesightmobile I think Ben is asking whether we can show that you can set traits when requesting the flags for an identity as this is the case in most of our SDKs. I'm not sure if that's the case here?

Yep this is what I meant - sorry wasnt clear. We need to show how to make a call where you Identify the user and provide some trait data (e.g. devicetype=iOS, version=3.4.1) and then get their flags back, all in 1 call.

**Comment by jackforesightmobile** [comment]
@dabeeeenster I discussed with @matthewelwell and there's no method for this currently on the iOS SDK. He said he's going to raise a separate ticket to implement this in another piece of work.

**Comment by matthewelwell** [comment]
@dabeeeenster @jackforesightmobile looks like it actually already exists [here](https://github.com/Flagsmith/flagsmith-ios-client/issues/43).

**Review by matthewelwell — APPROVED** [review]

**Pull request merged**
