### PR TITLE
WIP: improvement/store flags for selfhosted frontend

### PR DESCRIPTION
**Pull request by dabeeeenster**
# Overview

We want to be able to store the features associated with a version of the frontend code so that:

- We have reproducible builds that are not reliant on data from api.flagsmith.com
- We can control what features are in the Docker image by default

## How it works

We will store the flags that drive the front end feature set within our git repo. We can then update the frontend code to pull the flags from this local file rather than from api.flagsmith.com

## Versions

We now have additional environments in our Flagsmith on Flagsmith platform:

- `Production Docker`
- `Production EE`

We also have the following Docker image names and their associated Flagsmith environment mappings:

- `flagsmith/flagsmith-frontend-ee` - mapped to `Production EE`
- `flagsmith/flagsmith-frontend` - mapped to `Production Docker`
- `flagsmith/flagsmith` - mapped to `Production Docker`

### CODE REVIEW

**Comment by dabeeeenster** [comment]
@kyle-ssg we need to add the hook into the front end to pull from `/config/flags` when appropriate

**Comment by gabrielpra1** [comment]
Hey @dabeeeenster! I got here after seeing my self-hosted Flagsmith making external calls and landing on https://github.com/Flagsmith/flagsmith/issues/122. Is there a plan to get this released or what's the overall plan for the self-hosted version?

I also get a "You are using the staging environment" warning when running the docker version based on https://github.com/Flagsmith/self-hosted/blob/main/docker-compose.yml.

Thanks!

**Comment by dabeeeenster** [comment]
Yep - this work will happen in q2 2022!

**Comment by matthewelwell** [comment]
We discussed a slightly different approach to this and are tracking it under [this](https://github.com/Flagsmith/flagsmith/issues/646) ticket. This work is planned for this quarter.

**Pull request closed without merging**
