### PR TITLE
test: Do not merge - test Incrementing testcafe assertions timeout

### PR DESCRIPTION
**Pull request by novakzaballa**
Thanks for submitting a PR! Please check the boxes below:

- [ ] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [ ] I have filled in the "Changes" section below?
- [ ] I have filled in the "How did you test this code" section below?
- [ ] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

 test Incrementing testcafe assertions timeout

## How did you test this code?
Not tested.
Testing on Github actions

Do not merge!

### CODE REVIEW

**Comment by kyle-ssg** [comment]
The e2e isn't failing due to something as simple as assertion timeouts, the assertions are never falsey in the cases when they fail, as can be seen in the videos.

(Assertion timeouts are also configured globally in .testcaferc.js, at a rate that's already 20000ms)

**Comment by novakzaballa** [comment]
> 

@kyle-ssg were you able to replicate these E2E tests failures locally?

**Comment by kyle-ssg** [comment]
No, I'm spending a bit of today researching it, so far findings are here https://github.com/Flagsmith/flagsmith/issues/2679

**Comment by novakzaballa** [comment]
> No, I'm spending a bit of today researching it, so far findings are here #2679

My feeling is that TestCafe could be trying to click buttons that don't have yet the event listener attached.

**Pull request closed without merging**
