### PR TITLE
feat(permissions): manage permissions from a single location

### LINKED ISSUE #3501: UX Audit - Add ability to set permissions when creating a group, combine permissions and edit group
### Is your feature request related to a problem? Please describe.

I had to open this drawer to set permission of “create project” and “manage user groups” for this user group.

### Describe the solution you'd like.

I would expect to be able to set these permissions when I create the group, so I would add these settings to the creation drawer.

Similarly, editing the group (e.g. name, id, etc.) is separate from changing group permissions, but these could all be in one edit drawer

### Describe alternatives you've considered

N/A

### Additional context

_No response_

### LINKED ISSUE #3503: UX Audit - Allow setting of project and environment permissions at the organisation level
### Is your feature request related to a problem? Please describe.

Project permissions exist in each project’s settings screen, which was hard to find

### Describe the solution you'd like.

Having a way to set project permissions from the “Edit permissions” modal on organisation settings screen (/organisation-settings)

Perhaps have a project and environment tab in the org settings modal

### Describe alternatives you've considered

N/A

### Additional context

_No response_

### LINKED ISSUE #3619: Create group requires page refresh to show newly created group
See video: 

https://github.com/Flagsmith/flagsmith/assets/14089968/3c27dcc3-6504-4878-b990-3a8fd2bcbf53

### PR DESCRIPTION
**Pull request by kyle-ssg**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

- Organisation, project and environment settings can be managed in a single place for users, groups and roles
- Edit permissions happens without needing to press save (suggested in UX audit). This will start becoming a standard pattern with settings.
- All users, regardless of their role can access the permissions screen, they can manage whatever they are admin of (e.g.permissions for a group on an environment they are admin of)
- Previously, you had to navigate to separate areas to manage a group's users and their permissions, this is now combined
- Create / updating group no longer requires a refresh
- Dev experience: Migrates all groups functionality and OrganisationProvider to TypeScript/RTK
- Dev experience: Removes /organisation-groups, this was a page we showed specifically for MANAGE_GROUPS users, it is no longer needed. 
- Minor: Improves user list ui
- Minor: Toast messages no longer show duplicate consecutive messages

https://github.com/Flagsmith/flagsmith/assets/8608314/497c5efb-408c-48b6-a8df-453cba8fd2d6

**How I tested**

- Created / edited a group
- Managed organisation, project and environment permissions as an org admin
- Checked I couldn't edit permissions as a group admin without org permissions
- Made group admin a project admin, checked that they could manage permissions but just for that project

### CODE REVIEW

**Comment by matthewelwell** [comment]
@kyle-ssg this is super useful, I love it! 

I've noticed one fairly minor issue when editing environment permissions that there seems to be some stale data shown when switching between projects. Video example below. 

https://github.com/Flagsmith/flagsmith/assets/14089968/99dbf6ea-dad4-4824-8013-60a6ff8af930

What I guess I need to test next is around whether an admin for a specific environment can manage that environment's permissions from these new views.

**Comment by kyle-ssg** [comment]
@matthewelwell thanks, this is now fixed

**Comment by matthewelwell** [comment]
Another issue that I've found in testing: 

When you create a new project, and navigate straight to assign permissions for an environment in that project, the project does not appear in the drop down list of projects that you must choose the project from before choosing an environment. Note that it DOES appear in the list of projects. Video reproduction below. 

https://github.com/Flagsmith/flagsmith/assets/14089968/9e8ef1b9-ef0e-4418-a1a4-df2206aaecc9


I was also planning to test what an e.g. environment admin sees in this view but I can see that only organisation admins can see this view (which I think makes sense, at least for now).

**Comment by matthewelwell** [comment]
@kyle-ssg following the changes you made to allow env / project admins to see the members tab, I've noticed that the menu still shows which suggest these users can remove the user from the organisation. 

image

**Comment by kyle-ssg** [comment]
Right, makes sense -  this should be based on org admin

**Comment by kyle-ssg** [comment]
@matthewelwell this is done, users who can edit permissions but not remove users will see 
image

**Comment by matthewelwell** [comment]
@kyle-ssg one more bug found - it looks like it's not possible to remove (and maybe add, although I haven't tested this) users from / to groups. See the video below - it looks like it's not making any requests to `add-users` or `remove-users`. 

https://www.loom.com/share/169825ead4c24ad0b7d86675abce111b?sid=5f1f9a64-6516-4b92-a81e-dc264dc046a5

Note: I've tested this on production and it does work as expected so I think the bug has been introduced in this PR.

**Comment by kyle-ssg** [comment]
Yep correct, remove-users calls were missing. I've since tested adding and removing group users.

**Comment by matthewelwell** [comment]
Sorry, I think this is probably the last issue but it looks like we've lost the tags that we had previously on each of the entities that gave a summary of what permission a user had on that entity without having to open it up. 

This preview: 

image

Current production: 

image

**Review by matthewelwell — APPROVED** [review]
@kyle-ssg this looks good now (and seems to include the fix we talked about yesterday regarding showing the groups in a project settings) but I've updated the title of the PR as I don't think it should be a chore.

**Pull request merged**
