### PR TITLE
feat: Manage tags permission

### PR DESCRIPTION
**Pull request by kyle-ssg**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

Based on the feature flag manage_tags_permission, this will require MANAGE_TAGS rather than ADMIN permissions for creating,editing and removing tags

## How did you test this code?

Validate that the permission variables are set correctly, permission doesn't exist yet

### CODE REVIEW

**Comment by matthewelwell** [comment]
The PR to add the API logic is [here](https://github.com/Flagsmith/flagsmith/pull/4628). We should make sure that the API PR is merged and released first as it doesn't change the current behaviour (since it will fall back to just using project admin is a user doesn't have the MANAGE_TAGS permission).

**Comment by kyle-ssg** [comment]
@matthewelwell Actually that's fine since it's under the flag manage_tags_permission. Plus frontend would do the same too so I guess it's actually backwards compatible

**Comment by matthewelwell** [comment]
@kyle-ssg the tooltip on the 'Add Tag' button still refers to the 'Admin' permission. 

image

**Comment by kyle-ssg** [comment]
@matthewelwell done

**Review by matthewelwell — APPROVED** [review]

**Pull request merged**
