### PR TITLE
docs(api): document usage of endpoint_url on import/export

### PR DESCRIPTION
**Pull request by hamishhossack**
- [x] I have run [pre-commit](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

Updated documentation to include a pattern where using env vars for AWS endpoint URLs will allow users to import/export locally using localstack or similar.

## How did you test this code?

Docs change, no testing required

### CODE REVIEW

**Comment by matthewelwell** [comment]
@hamishhossack it seems that the conflicts still exist? Can you also ensure the name of the PR follows the correct convention?

**Comment by hamishhossack** [comment]
> @hamishhossack it seems that the conflicts still exist? Can you also ensure the name of the PR follows the correct convention?

all sorted and squashed commits :+1:

**Comment by matthewelwell** [comment]
@hamishhossack sorry, I think the workflows failed due to some issues in the main branch which should now be resolved - can you rebase / merge again? 🙏

**Comment by gagantrivedi** [comment]
@hamishhossack can you rebase it on main one last time please - boto was updated here: https://github.com/Flagsmith/flagsmith/pull/2926

**Comment by hamishhossack** [comment]
@gagantrivedi This PR seems obsolete now since this [other PR](https://github.com/Flagsmith/flagsmith/pull/2926) has upgraded boto3..

You might want to have the documented approach for using endpoint_url in Flagsmith so I'll rebase and let you decide on the PR going forward.

I'll use the version that was provided in the other PR since it's compatible and there will be fewer conflicts in this PR if it says alive..

**Comment by gagantrivedi** [comment]
> @gagantrivedi This PR seems obsolete now since this [other PR](https://github.com/Flagsmith/flagsmith/pull/2926) has upgraded boto3..
> 
> You might want to have the documented approach for using endpoint_url in Flagsmith so I'll rebase and let you decide on the PR going forward.
> 
> I'll use the version that was provided in the other PR since it's compatible and there will be fewer conflicts in this PR if it says alive..

Yeah, you can turn this into a docs PR - that would be great

**Review by matthewelwell — APPROVED** [review]

**Comment by dabeeeenster** [comment]
Closed in favour of https://github.com/Flagsmith/flagsmith/pull/2959

**Pull request closed without merging**
