### PR TITLE
ci: release please

### PR DESCRIPTION
**Pull request by dabeeeenster**
~~NOTE: Need to create a `RELEASE_PLEASE_GITHUB_TOKEN` as per https://github.com/google-github-actions/release-please-action#github-credentials so that tagging can trigger other workflows~~ 

This PR adds linting for [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) PR titles and then leverages them to do automated Release PRs with https://github.com/google-github-actions/release-please-action.

We don't need to touch our other production actions as they trigger on on tags being created, which the release-please action will carry out.

### CODE REVIEW

**Comment by matthewelwell** [comment]
@khvn26 I think we need to introduce [this](https://github.com/amannn/action-semantic-pull-request) before we start using release please, right?

**Comment by khvn26** [comment]
@matthewelwell looks like it's included here. Did you mean that we should merge the PR title check first?

**Comment by matthewelwell** [comment]
> @matthewelwell looks like it's included here. Did you mean that we should merge the PR title check first?

Sorry, I should use my eyes...! 👀 ignore my comment. 

@dabeeeenster could you update the description to actually confirm what this change will do. How will release please work for this repository?

**Comment by dabeeeenster** [comment]
> > @matthewelwell looks like it's included here. Did you mean that we should merge the PR title check first?
> 
> Sorry, I should use my eyes...! 👀 ignore my comment.
> 
> @dabeeeenster could you update the description to actually confirm what this change will do. How will release please work for this repository?

Updated

**Review by matthewelwell — APPROVED** [review]

**Pull request merged**
