### PR TITLE
feat: Add tag based permissions

### LINKED ISSUE #1535: WIP: More granular feature level permissions
# Overview

Where larger teams are working on a single Flagsmith Project, it would be useful for them to be able to assign RBAC privieldges based on a subset of Flags within the Project. 

# Potential Solution

The current proposed solution involves leveraging the tags that already exist within the platform. We would add the ability, when modifying the permissions for a group in an environment, to add a subset of tags that that permission / those permissions apply to. For example, you may have a group of users that should only have the 'Update feature state' permission against a subset of tags. One UI option to illustrate this is to add the ability to add tags below each permission, as per the following screenshot.

Screenshot 2023-02-08 at 11 41 30

# Detailed Example

TBC

# Issues/Open Questions

- Who defines what tag a Flag is associated with?
- Would this require a new concept of 'Roles'? Currently we only have the concept of groups which means that users will likely belong to more than one group. 
- Is there a way we can allow existing customers to migrate?
- Should we have a setting against the project which enables these tag-based permissions for the project?
- Should we only allow the management of tag based permissions for a group? This seems to make sense since customers that want to use permissions on such a granular level are likely using groups exclusively anyway.

# Other Possible Approaches

### Environment / Feature Combination Level Permissions

The tags approach makes the management of the permissions slightly simpler, however, it may not be the best solution for creating the most granular permissions. Another option here would be to allow admins to create permissions for groups (& users?) against a combination of a feature and an environment. The UI management of these permissions would be challenging but it would likely allow admins to create more granular permissions as needed.

### LINKED ISSUE #4424: Restrict Permissions Based on Tags in Roles
**FE Restrictions:**

- When a tag is added to a role, the FE should automatically disable any other permissions that are not compatible with the tag.

**API Validation:**

- The API should reject the creation of any role that has a tag associated with unsupported permissions.

- The API response for the /{entity}/permissions/ endpoints (where entity can be projects or environments) should include information about these validation errors.

### PR DESCRIPTION
**Pull request by kyle-ssg**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

Supersedes https://github.com/Flagsmith/flagsmith/pull/4250

Users can now create tag-based roles
image

A tag based role will let you specify relevant permissions

image

image

## How did you test this code?

The frontend will check for any tag-based permissions if it cannot find any standard permissions. In this example my user can only update feature states for the marketing tag.

https://github.com/user-attachments/assets/9b8fe88d-8848-46bf-915b-b98ba7eea851

Needs https://github.com/Flagsmith/flagsmith/issues/4799 to be implemented in order for it to work fully.

### CODE REVIEW

**Comment by rolodato** [comment]
I don't understand how this is supposed to be used based on the docs description.

From what I understand, this functionality allows defining feature-level permissions so that only specific users can modify certain sensitive features. Happy to collaborate on these docs but I'd like to sync and understand how this functionality actually works first.

**Comment by kyle-ssg** [comment]
> I don't understand how this is supposed to be used based on the docs description.
> 
> From what I understand, this functionality allows defining feature-level permissions so that only specific users can modify certain sensitive features. Happy to collaborate on these docs but I'd like to sync and understand how this functionality actually works first.

It's quite hard to describe but it does work as updated in the docs. 

If permissions are tagged, the following permissions will only be granted on features with matching tags:
- Create feature, Update Feature, Segment Overrides, and Change Requests

If a user has admin permissions from another role or group it'll grant the user the missing permissions.

**Comment by kyle-ssg** [comment]
@gagantrivedi cc just to confirm, were the missing permissions added? This used to be just update feature and segment override

**Comment by gagantrivedi** [comment]
> @gagantrivedi cc just to confirm, were the missing permissions added? This used to be just update feature and segment override

No, they are not added yet

**Pull request closed without merging**
