### PR TITLE
Add test support for envs

### PR DESCRIPTION
**Pull request by sjdines**
Allow support for Django 2+ and Python 3.5 / 3.6 in a tested environment.

To run tests just install the `requirements-local.txt` as per normal and run `tox`.

### CODE REVIEW

**Comment by matthewelwell** [comment]
@sjdines I've been trying to get this to work in the new pipenv environment and was having some issues but I've just checked out the naked branch and tried to run it using a standard virtualenv and I'm getting similar issues. 

This is the error that I'm seeing when running it from your branch or my half merged branch. 

```
django111-py27 runtests: commands[1] | coverage report
Name    Stmts   Miss  Cover   Missing
-------------------------------------
No data to report.
ERROR: InvocationError for command '/Users/mattelwell/Documents/projects/sjdines/bullet-train-api/.tox/django111-py27/bin/coverage report' (exited with code 1)
```

I imagine that `coverage report` command should display a list of all the files and their test coverage?

**Comment by sjdines** [comment]
@matthewelwell I will have to rework some of this as pipenv is ensuring that Django 1.11 is installed rather than changing the Django versions as desired. The coverage is not being displayed as I forgot to put in a call for `coverage combine` which adds all the coverage results together after being run in parallel.

I will try to get to this when I get a chance but will probably take a few days.

**Comment by matthewelwell** [comment]
No worries. Thanks @sjdines. Again, let me know if I can help in any way.

**Comment by sjdines** [comment]
@matthewelwell I finally got to doing this! Please let me know if you have any feedback

**Comment by matthewelwell** [comment]
@sjdines great, thanks! I'll try to take a look over the weekend.

**Comment by sjdines** [comment]
@matthewelwell np at all about the delay. That does seem strange. I don't recall any pinned requirements for tox. I'll try to investigate in the next few days and get back to you

**Comment by matthewelwell** [comment]
That's great, thanks Stuart. Please let me know if there's anything I can do to help you.

**Pull request closed without merging**
