### PR TITLE
Add support for SES as email provider

### PR DESCRIPTION
**Pull request by julada**

### CODE REVIEW

**Comment by dabeeeenster** [comment]
Hey @julada thanks so much for this 👍  we'll take a look and hopefully merge in in the next few days

**Comment by julada** [comment]
> Hey @julada thanks so much for this 👍 we'll take a look and hopefully merge in in the next few days

Hey @dabeeeenster, any progress on this?

**Review by dabeeeenster — COMMENTED** [review]
Thanks for this. Are you able to update the readme to explain how to override Sendgrid with SES using environment variables? Thanks!

**Comment by julada** [comment]
> Thanks for this. Are you able to update the readme to explain how to override Sendgrid with SES using environment variables? Thanks!

sorry for the late reply. i added the documentation.

**Comment by dabeeeenster** [comment]
Do we not need to add these (from django-SES docs)

```
# These are optional -- if they're set as environment variables they won't
# need to be set here as well
AWS_ACCESS_KEY_ID = 'YOUR-ACCESS-KEY-ID'
AWS_SECRET_ACCESS_KEY = 'YOUR-SECRET-ACCESS-KEY'
```

**Comment by julada** [comment]
> Do we not need to add these (from django-SES docs)
> 
> ```
> # These are optional -- if they're set as environment variables they won't
> # need to be set here as well
> AWS_ACCESS_KEY_ID = 'YOUR-ACCESS-KEY-ID'
> AWS_SECRET_ACCESS_KEY = 'YOUR-SECRET-ACCESS-KEY'
> ```

These are only needed as system environment variables. If you host the bullet train instance on an EC2 machine the credentials are automatically provided by the assigned role.

EDIT: You already allow the usage of S3 buckets in AWS. these require the credentials as well, so I didn't document that. I could add a hint if you want so.

**Pull request merged**
