### PR TITLE
improvement/api-audit

### PR DESCRIPTION
**Pull request by dabeeeenster**
Runs `pip-audit` once a day to check for security issues in dependencies

### CODE REVIEW

**Comment by matthewelwell** [comment]
Is this instead of dependabot then?

**Comment by dabeeeenster** [comment]
No it's in addition.

**Comment by matthewelwell** [comment]
> No it's in addition.

... can you explain why we need both? Looks like this is checking dev dependencies as well perhaps? But then surely we don't need dependabot. Maybe dependabot is good from a visibility point of view?

**Comment by dabeeeenster** [comment]
Dependabot only runs once a week AFAIK. `pip-audit` is backed by Google and appears to be the new standard for python scanning. We should scan dev dependencies as their code runs on our machines!

**Comment by matthewelwell** [comment]
Everything you're saying seems to suggest we should just use this and turn dependabot off then?

**Comment by dabeeeenster** [comment]
Yeah we could do - but tbh I don't see what harm there is running both?

**Comment by matthewelwell** [comment]
Probably none, yeah, but it's good to understand what the differences are.  Let's go with both and see.

**Review by matthewelwell — APPROVED** [review]

**Pull request merged**
