### PR TITLE
feat: Enabled state filter (Frontend)

### LINKED ISSUE #3243: Filter flags in dashboard based on flag state
It would be useful to be able to filter flags based on both their boolean and text values. Suggest adding another dropdown here titled "State" which opens a drop down to allow this:

image

### PR DESCRIPTION
**Pull request by kyle-ssg**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

Frontend functionality for filtering feature enabled state and feature value, based on https://github.com/Flagsmith/flagsmith/pull/3541. This is controlled by the feature flag **feature_enabled_state_filter**.

image

Note: I believe the API is searching based on the project default_value/default_enabled, it should be based on the provided environment's feature state. We'd never want to filter based on defaults.

## How did you test this code?
- Search a feature by value / enabled state

### CODE REVIEW

**Review by zachaysan — COMMENTED** [review]
The code looks good thus far, but just wanted to confirm that we're designing in a search field as well to match feature values based on boolean, string, and integer values.

**Comment by kyle-ssg** [comment]
It’s an easy addition but I couldn’t imagine that common a use case , thinking about itI’ll do it as part of this pr

**Review by zachaysan — APPROVED** [review]
Code looks good, but please hold off on merging this until the server issue you highlighted gets fixed.

Edit: Or wrap this all up under a feature flag so we can deploy and fix whenever we want.

**Comment by kyle-ssg** [comment]
Yep its under a feature flag.

**Pull request merged**
